app:
  id: replace_with_app_id
  apiKey: replace_with_api_key
  globalFQDN: dnaservices.cisco.com
  regionalFQDNs:
  - neoffers.cisco.com
  readStream: replace_with_read_stream
  writeStream: replace_with_write_stream

tenant:
  otp: replace_with_otp_from_dna_cloud
  # config file will be rewritten with id, name and token after using OTP
  id:
  name:
  token:
