name: Static Analysis
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v7
        with:
          go-version: 1.25.x
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          # Use the latest stable golangci-lint release supported by this action.
          version: latest

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
